import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '@/styles/reset.css'
import './globals.css'
import Header from "@/components/Header/index";
import { Poppins } from 'next/font/google'

const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin']
})


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
        <Header />
        <main className={poppins.className}>{children}</main>
      </body>
    </html>
  );
}
